"""Add encrypted columns for full_name and phone to users table"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20230830_add_encrypted_columns"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')
    # ### end Alembic commands ###
