"""add_otp_columns

Revision ID: 7de558c1e5ce
Revises: ae138f43fe0f
Create Date: 2026-09-01 13:17:35.002085
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7de558c1e5ce'
down_revision: Union[str, None] = 'ae138f43fe0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'verification_otp')
    # ### end Alembic commands ###
