"""full_schema

Revision ID: ae138f43fe0f
Revises: 20230830_add_encrypted_columns
Create Date: 2026-09-01 11:34:14.507989
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ae138f43fe0f'
down_revision: Union[str, None] = '20230830_add_encrypted_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
